services:
  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/site1.conf:/etc/nginx/conf.d/site1.conf
      - ./nginx/site2.conf:/etc/nginx/conf.d/site2.conf
      - ./nginx/site3.conf:/etc/nginx/conf.d/site3.conf
      - ./nginx/auth/.htpasswd:/etc/nginx/.htpasswd
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/html:/usr/share/nginx/html
    depends_on:
      - keycloak
      - site3-backend
    restart: unless-stopped
    networks:
      - mynetwork

  keycloak:
    platform: linux/amd64
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-server
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=keycloak-server
      - KC_PROXY=edge
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false   
      - KC_SSL_REQUIRED=external  # Allow HTTP for now
      - KC_HTTP_ENABLED=true  # Allow HTTP (if not using HTTPS yet)
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    ports:
      - "8080:8080"
    networks:
      - mynetwork

  site3-backend:
    image: nginx:latest
    container_name: site3-backend
    volumes:
      - ./nginx/html/site3:/usr/share/nginx/html
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge