services:
  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/site1.conf:/etc/nginx/conf.d/site1.conf
      - ./nginx/site2.conf:/etc/nginx/conf.d/site2.conf
      - ./nginx/site3.conf:/etc/nginx/conf.d/site3.conf
      - ./nginx/auth/.htpasswd:/etc/nginx/.htpasswd
      - ./nginx/html:/usr/share/nginx/html
    restart: unless-stopped